### ISSUE TITLE
by link? 

### ISSUE THREAD

**Issue by dragon1x** [swagkarna/steal-audio#1]

**Comment by swagkarna** [comment]
Yes see this repo  https://github.com/swagkarna/Nivistealer

**Comment by dragon1x** [comment]
great tool

في الجمعة، ٤ مارس ٢٠٢٢ ١٠:١٨ ص swagkarna ***@***.***> كتب:

**Comment by dragon1x** [comment]
The images are saved, but the audio or location is not

في الجمعة، ٤ مارس ٢٠٢٢ ١٠:٢٦ ص Dragon xxx ***@***.***> كتب:
